# Generated by Django 5.1.3 on 2025-08-11 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_collection_productmedia_collectionentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('gallery', 'Gallery'), ('detail', 'Detail')], default='gallery', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='base.productmedia')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='base.product')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('product', 'media')},
            },
        ),
    ]
